### PR TITLE
Adding documentation and additional command line options to ascp.sh

### PR DESCRIPTION
**Pull request by gwaybio**
Thanks for releasing this docker file, and providing documentation for use on the [IDR website](https://idr.openmicroscopy.org/about/download.html).

I'd like to use the docker command to download images of individual plates, but it is likely that the hardcoded limit of 40m will prevent complete downloads. 

https://github.com/IDR/aspera-client-docker/blob/888540176f36bc5f6878da59df9f4037cc693f3e/Dockerfile#L19

In this PR, I've added an option to run the docker image with an *optional* fourth command line argument to enable the user to specify the limit. This option is available for directly using the `ascp` command, but I'd prefer to contain this interaction inside docker.

Thanks!

### CODE REVIEW

**Comment by gwaybio** [comment]
cc @sbesson and @will-moore - thanks for your expertise in the past! I'd love to get this working :)

**Comment by gwaybio** [comment]
Here is my timeout error:

```bash
r11c15f09p01-ch5sk1fk1fl1.tiff                                                                             100% 9129KB 37.2Mb/s    42:29
r11c16f09p01-ch1sk1fk1fl1.tiff                                                                              62% 5737KB           - stalled -Partial Completion: 11675019K bytes transferred in 2611 seconds
 (36616K bits/sec), in 1565 files, 2 directories; 288 files failed.

Session Stop  (Error: Session data transfer timeout (server), Session data transfer timeout)
```

**Comment by joshmoore** [comment]
Hi Greg. Did you try passing docker an environment variable? I would _think_ that:

```
docker run ... -e ASCP_LIMIT=10m imagedata/download ...
```

for example, should get you what you want (and should really be in the README!) If you think there's still an advantage to adding an additional override option, let us know.

~J.

**Comment by gwaybio** [comment]
Great point! I am a bit embarrassed to say that I hadn't thought about it :)

## Me learning what `-l` is _actually_ doing

I've tested it out, it works, but in my testing, discovered something else: I was wrong to assume what `-l` is doing!

I assumed that the `40m` notation meant 40 minutes (which I thought was confirmed by my download timing out at ~40 min). However, based on the [aspera documentation](https://www.ibm.com/docs/en/aci/3.9.2?topic=ascp-command-reference), `-l` is actually `max_rate`. This is huge!

```
-l max_rate
    Transfer at rates up to the specified target rate. (Default: 10000 Kbps)
    This option accepts suffixes "G" or "g" for giga, "M" or "m" for mega, "K" or "k" for kilo,
    and "P", "p", or "%" for percentage. Decimals are allowed. If this option is not set
    by the client, the setting in the server's aspera.conf is used. If a rate cap is set in the local
    or server aspera.conf, the rate does not exceed the cap. 
```

## Expose `-k` parameter to user

In reviewing more of the documentation, I think we should expose more parameters to the user during download.

For example, `-k 1` might be nice:

```
-k {0|1|2|3}
    Enable the resuming of partially transferred files at the specified resume level. (Default: 0)

    Specify this option for the first transfer or it will not work for subsequent transfers. Resume levels:

        -k 0 – Always re-transfer the entire file.
        -k 1 – Compare file attributes and resume if they match, and re-transfer if they do not.
        -k 2 – Compare file attributes and the sparse file checksums; resume if they match, and re-transfer if they do not.
        -k 3 – Compare file attributes and the full file checksums; resume if they match, and re-transfer if they do not.

    If a complete file exists at the destination (no .aspx), the source and destination file sizes are compared. If a partial file and a valid .aspx file exist at the destination, the source file size and the file size recorded in the .aspx file are compared. 
```

## Potential modifications to `ascp.conf`

Also, I think my 40 min timeout was a coincidence. `-k 1` will help, but we may need some updates to the `ascp.conf` file, which, I assume is hidden to the user. [Here is the documentation that might also help solve this](https://www.ibm.com/docs/en/ahts/4.0?topic=t-error-session-timeout-during-ascp-transfers).

## Pull request changes

- I wouldn't mind having the ability explicitly set the `ASCP_OPTION_LIMIT`, but I agree it is kinda redundant with the ability to pass through a docker environment variable.
- I also agree that this should be specified in the README :)
- I think we should add `-k $VAR` of sorts

I can make these change in the PR if you'd like. Thanks again!

**Comment by gwaybio** [comment]
Alright, some proposed changes added, ready for re-review @joshmoore

**Comment by joshmoore** [comment]
Briefly, changes look great. From our side, I could see looking into allow passing _all_ `ascp` arguments, but it will need some care to keep backwards compatibility.

**Comment by gwaybio** [comment]
Sounds good! Thanks @joshmoore!

I agree that passing all args in the future would be preferred, but for now, is it sufficient for merging?

**Review by sbesson — APPROVED** [review]

**Comment by joshmoore** [comment]
Done. Thanks, @gwaygenomics!

**Comment by gwaybio** [comment]
Thank you @joshmoore and @sbesson !

When you get a chance, can you push this version to dockerhub?

**Comment by joshmoore** [comment]
Is it not there? ..._checks_... You're right! (https://hub.docker.com/r/imagedata/download/tags)

We'll look into what went sideways. Thanks for the heads up.

**Comment by sbesson** [comment]
@gwaygenomics `imagedata/download:0.3.1` should now be available from DockerHub

**Comment by gwaybio** [comment]
I see it there - thanks @sbesson !

**Pull request merged**
